//+------------------------------------------------------------------+
//| FinRL-X-MT5 Expert Advisor                                       |
//| K-Dense Council — MoE Trading System                             |
//| Instruments: NAS100/USTEC, USOIL, XAUUSD, US30                  |
//|                                                                  |
//| BACKTEST MODE: Every Tick Based on Real Ticks                    |
//|                                                                  |
//| This EA receives signals from the Python Council via a shared    |
//| file bridge (signals.json) or direct socket connection.          |
//| In backtest mode, signals are pre-generated by Python and        |
//| read from a CSV file aligned to bar timestamps.                  |
//+------------------------------------------------------------------+

#property copyright "FinRL-X-MT5 K-Dense Council"
#property version   "1.00"
#property strict

#include <Trade\Trade.mqh>
#include <Trade\PositionInfo.mqh>
#include <Trade\SymbolInfo.mqh>

// ─── Input Parameters ──────────────────────────────────────────────────────
input group "=== Council Signal ========================="
input string   SignalFile      = "finrl_x_signals.csv";  // Signal file path (Experts\Files\)
input int      MagicNumber     = 20260908;                // EA Magic Number
input string   TradeComment    = "FinRL-X-MT5";           // Order comment

input group "=== Risk Management ========================"
input double   RiskPctPerTrade = 2.0;    // Risk % per trade (of balance)
input double   MaxDrawdownPct  = 10.0;   // Max DD % before halt
input double   MinFreeMarginPct = 30.0;  // Min free margin %
input double   SpreadMultiplier = 3.0;   // Spread spike multiplier filter

input group "=== Signal Thresholds ======================"
input double   MinSignalStrength  = 0.20;  // Min |signal| to open trade
input double   MinConfidence      = 0.40;  // Min council confidence
input double   MinExpectedRR      = 1.50;  // Min expected Risk:Reward

input group "=== Timeframe ================================"
input ENUM_TIMEFRAMES TradingTF = PERIOD_M5;  // Trading timeframe

// ─── Global Variables ─────────────────────────────────────────────────────
CTrade         Trade;
CPositionInfo  PositionInfo;
CSymbolInfo    SymbolInfo;

datetime g_LastBarTime   = 0;
bool     g_TradingHalted = false;
int      g_SignalHandle  = INVALID_HANDLE;

// Signal struct loaded from Python CSV output
struct CouncilSignal {
   datetime  bar_time;
   double    consensus_signal;   // ∈ [-1, 1]
   int       direction;          // +1=long, -1=short, 0=flat
   double    position_size;      // ∈ [0, 1]
   double    tp_price;
   double    sl_price;
   double    expected_rr;
   double    confidence;
   string    regime;             // "BULL" | "BEAR" | "SIDEWAYS"
};

// Signal cache (loaded from CSV)
CouncilSignal g_Signals[];
int           g_SignalCount = 0;
int           g_SignalIdx   = 0;

//+------------------------------------------------------------------+
//| Expert initialization                                             |
//+------------------------------------------------------------------+
int OnInit() {
   Trade.SetExpertMagicNumber(MagicNumber);
   Trade.SetDeviationInPoints(20);
   Trade.SetTypeFilling(ORDER_FILLING_IOC);
   
   Print("🏛️ K-Dense Council EA initialized");
   Print("   Magic: ", MagicNumber);
   Print("   Signal file: ", SignalFile);
   Print("   Risk per trade: ", RiskPctPerTrade, "%");
   
   // Load signals from Python-generated CSV
   if (!LoadSignals()) {
      Print("⚠️  No signal file found — will use live Python bridge");
      // In live mode, signals come via file bridge updated every M5
   }
   
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization                                           |
//+------------------------------------------------------------------+
void OnDeinit(const int reason) {
   Print("K-Dense Council EA stopped. Reason: ", reason);
}

//+------------------------------------------------------------------+
//| Expert tick function                                              |
//+------------------------------------------------------------------+
void OnTick() {
   // New bar detection
   datetime current_bar = iTime(_Symbol, TradingTF, 0);
   if (current_bar == g_LastBarTime) return;
   g_LastBarTime = current_bar;
   
   // Safety checks
   if (g_TradingHalted) {
      Comment("⛔ TRADING HALTED — Drawdown limit reached");
      return;
   }
   
   if (!CheckRiskLimits()) return;
   
   // Get current Council signal for this bar
   CouncilSignal signal;
   if (!GetCurrentSignal(current_bar, signal)) return;
   
   // Apply signal thresholds
   if (MathAbs(signal.consensus_signal) < MinSignalStrength) return;
   if (signal.confidence < MinConfidence)                    return;
   if (signal.expected_rr < MinExpectedRR)                   return;
   if (signal.direction == 0)                                return;
   
   // Spread spike filter
   if (!CheckSpread()) return;
   
   // Execute trade
   ExecuteCouncilSignal(signal);
}

//+------------------------------------------------------------------+
//| Load pre-computed signals from Python CSV                         |
//| CSV format (generated by Python Council):                         |
//| time,consensus_signal,direction,position_size,tp,sl,rr,conf,regime|
//+------------------------------------------------------------------+
bool LoadSignals() {
   string filepath = "finrl_x_mt5\\" + SignalFile;
   int handle = FileOpen(filepath, FILE_READ | FILE_CSV | FILE_ANSI, ',');
   
   if (handle == INVALID_HANDLE) {
      return false;
   }
   
   // Skip header
   if (!FileIsEnding(handle)) {
      string header = FileReadString(handle);
      FileReadString(handle);  // newline
   }
   
   int count = 0;
   ArrayResize(g_Signals, 10000);
   
   while (!FileIsEnding(handle) && count < 10000) {
      CouncilSignal s;
      string time_str        = FileReadString(handle);
      s.consensus_signal     = FileReadNumber(handle);
      s.direction            = (int)FileReadNumber(handle);
      s.position_size        = FileReadNumber(handle);
      s.tp_price             = FileReadNumber(handle);
      s.sl_price             = FileReadNumber(handle);
      s.expected_rr          = FileReadNumber(handle);
      s.confidence           = FileReadNumber(handle);
      s.regime               = FileReadString(handle);
      
      s.bar_time = StringToTime(time_str);
      g_Signals[count++] = s;
   }
   
   FileClose(handle);
   g_SignalCount = count;
   Print("📋 Loaded ", count, " Council signals from CSV");
   return count > 0;
}

//+------------------------------------------------------------------+
//| Get Council signal for current bar                                |
//+------------------------------------------------------------------+
bool GetCurrentSignal(datetime bar_time, CouncilSignal &signal) {
   // CSV mode: find matching bar
   if (g_SignalCount > 0) {
      while (g_SignalIdx < g_SignalCount) {
         if (g_Signals[g_SignalIdx].bar_time >= bar_time) {
            if (g_Signals[g_SignalIdx].bar_time == bar_time) {
               signal = g_Signals[g_SignalIdx];
               g_SignalIdx++;
               return true;
            }
            break;
         }
         g_SignalIdx++;
      }
      return false;
   }
   
   // Live mode: read from bridge file (updated by Python every M5)
   return ReadLiveBridgeSignal(signal);
}

//+------------------------------------------------------------------+
//| Read live signal from Python bridge file                          |
//+------------------------------------------------------------------+
bool ReadLiveBridgeSignal(CouncilSignal &signal) {
   string filepath = "finrl_x_mt5\\live_signal.json";
   int handle = FileOpen(filepath, FILE_READ | FILE_TXT | FILE_ANSI);
   if (handle == INVALID_HANDLE) return false;
   
   string json = "";
   while (!FileIsEnding(handle))
      json += FileReadString(handle);
   FileClose(handle);
   
   // Simple JSON parsing (key-value extraction)
   signal.consensus_signal = ExtractJsonDouble(json, "consensus_signal");
   signal.direction        = (int)ExtractJsonDouble(json, "direction");
   signal.position_size    = ExtractJsonDouble(json, "position_size");
   signal.tp_price         = ExtractJsonDouble(json, "tp_price");
   signal.sl_price         = ExtractJsonDouble(json, "sl_price");
   signal.expected_rr      = ExtractJsonDouble(json, "expected_rr");
   signal.confidence       = ExtractJsonDouble(json, "confidence");
   signal.regime           = ExtractJsonString(json, "regime");
   signal.bar_time         = TimeCurrent();
   
   return true;
}

//+------------------------------------------------------------------+
//| Execute Council signal as MT5 order                               |
//+------------------------------------------------------------------+
void ExecuteCouncilSignal(CouncilSignal &signal) {
   double equity  = AccountInfoDouble(ACCOUNT_EQUITY);
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double price   = signal.direction > 0 ? SymbolInfoDouble(_Symbol, SYMBOL_ASK)
                                         : SymbolInfoDouble(_Symbol, SYMBOL_BID);
   
   // Compute lot size
   double lots = ComputeLots(signal, equity, price);
   if (lots <= 0) return;
   
   // Close opposite position first
   CloseOppositePosition(signal.direction);
   
   // Set SL/TP (validate they are on correct side of price)
   double sl = signal.sl_price;
   double tp = signal.tp_price;
   
   // Normalize to symbol digits
   int digits = (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS);
   sl = NormalizeDouble(sl, digits);
   tp = NormalizeDouble(tp, digits);
   
   string comment = TradeComment + "|" + signal.regime + "|" +
                    DoubleToString(signal.consensus_signal, 3);
   
   bool result = false;
   if (signal.direction > 0) {
      result = Trade.Buy(lots, _Symbol, price, sl, tp, comment);
   } else {
      result = Trade.Sell(lots, _Symbol, price, sl, tp, comment);
   }
   
   if (result) {
      Print("✅ Order executed: ",
            (signal.direction > 0 ? "BUY " : "SELL "),
            DoubleToString(lots, 2), " lots @ ", DoubleToString(price, digits),
            " | SL=", DoubleToString(sl, digits),
            " | TP=", DoubleToString(tp, digits),
            " | Signal=", DoubleToString(signal.consensus_signal, 3),
            " | Regime=", signal.regime);
   } else {
      Print("❌ Order failed: ", Trade.ResultRetcodeDescription());
   }
}

//+------------------------------------------------------------------+
//| Risk checks                                                        |
//+------------------------------------------------------------------+
bool CheckRiskLimits() {
   double equity    = AccountInfoDouble(ACCOUNT_EQUITY);
   double balance   = AccountInfoDouble(ACCOUNT_BALANCE);
   double free_mgn  = AccountInfoDouble(ACCOUNT_MARGIN_FREE);
   
   // Drawdown halt
   if (balance > 0) {
      double dd = 1.0 - equity / balance;
      if (dd * 100 > MaxDrawdownPct) {
         g_TradingHalted = true;
         Print("🛑 DRAWDOWN HALT: ", DoubleToString(dd * 100, 2),
               "% > ", MaxDrawdownPct, "%");
         return false;
      }
   }
   
   // Free margin check
   if (equity > 0 && free_mgn / equity * 100 < MinFreeMarginPct) {
      Print("⛔ Insufficient free margin: ",
            DoubleToString(free_mgn / equity * 100, 1), "%");
      return false;
   }
   
   return true;
}

bool CheckSpread() {
   long spread = SymbolInfoInteger(_Symbol, SYMBOL_SPREAD);
   // Check spread against multiplier threshold
   return (spread <= (long)(SpreadMultiplier * 50));
}

//+------------------------------------------------------------------+
//| Lot sizing: Council signal → MT5 lots                             |
//+------------------------------------------------------------------+
double ComputeLots(CouncilSignal &signal, double equity, double price) {
   double dollar_risk = equity * RiskPctPerTrade / 100.0 * signal.position_size;
   double contract    = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_CONTRACT_SIZE);
   double lot_raw     = dollar_risk / (price * contract + 0.0001);
   
   double min_lot  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double max_lot  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   double lot_step = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   
   double lots = MathMax(min_lot, MathMin(max_lot,
                  MathRound(lot_raw / lot_step) * lot_step));
   return NormalizeDouble(lots, 2);
}

//+------------------------------------------------------------------+
//| Close opposite position if exists                                  |
//+------------------------------------------------------------------+
void CloseOppositePosition(int new_direction) {
   for (int i = PositionsTotal() - 1; i >= 0; i--) {
      if (PositionSelectByTicket(PositionGetTicket(i))) {
         if (PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
         if (PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
         
         int pos_type = (int)PositionGetInteger(POSITION_TYPE);
         int pos_dir  = (pos_type == POSITION_TYPE_BUY) ? 1 : -1;
         
         if (pos_dir != new_direction) {
            Trade.PositionClose(PositionGetInteger(POSITION_TICKET));
            Print("🔄 Closed opposite position: Ticket=",
                  PositionGetInteger(POSITION_TICKET));
         }
      }
   }
}

//+------------------------------------------------------------------+
//| Simple JSON helpers                                                |
//+------------------------------------------------------------------+
double ExtractJsonDouble(string json, string key) {
   string search = "\"" + key + "\":";
   int pos = StringFind(json, search);
   if (pos < 0) return 0.0;
   pos += StringLen(search);
   return StringToDouble(StringSubstr(json, pos, 20));
}

string ExtractJsonString(string json, string key) {
   string search = "\"" + key + "\":\"";
   int pos = StringFind(json, search);
   if (pos < 0) return "";
   pos += StringLen(search);
   int end = StringFind(json, "\"", pos);
   if (end < 0) return "";
   return StringSubstr(json, pos, end - pos);
}
